### ISSUE TITLE
Dzen.ru

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#245]
Tried adding `dzen.ru` embedding for no avail.

Dzen.ru itself offers the following code to embed this very video:
```html
<iframe width="480" height="270" src="https://dzen.ru/embed/vj_7LeHg1QEA?from_block=partner&from=zen&mute=0&autoplay=0&tv=0" allow="autoplay; fullscreen; accelerometer; gyroscope; picture-in-picture; encrypted-media" data-testid="embed-iframe" frameborder="0" scrolling="no" allowfullscreen></iframe>
```

The `dzen.yml` is the following
```yaml
name: "Dzen"
host: dzen.ru
example: https://dzen.ru/video/watch/639af70a4cb0c65b51c4b724
scrape:
    - match: "!dzen\\.ru/video/watch/[\\w]+!"
    - extract: "#meta property=\"twitter:player:stream\" content=\".*?dzen.ru/embed/(?'id'[\\w]+)#"
    - header: "User-agent: FreeBSD/11.0 Lynx/56"
iframe:
    width: "100%"
    height: "270"
    src: //dzen.ru/embed/{@id}
    data-testid: "embed-iframe"
    allow: "autoplay; fullscreen; accelerometer; gyroscope; picture-in-picture; encrypted-media"
    from: "zen"
    from_block: "partner"
```

But the response (taken from the textformatter cache gz) is:
```
HTTP/1.1 302 Found
Content-Length: 0
Content-Type: application/json;charset=utf-8
Date: Sun, 23 Mar 2025 04:42:56 GMT
Location: https://sso.passport.yandex.ru/push?uuid=0f17899e-a473-491f-94d3-8dd4cb6f9cc1&retpath=https%3A%2F%2Fdzen.ru%2Fvideo%2Fwatch%2F639af70a4cb0c65b51c4b724%3Fis_autologin_ya%3Dtrue
Set-Cookie: zencookie=5621611251742704976; Path=/; Domain=.dzen.ru; Expires=Wed, 21-Mar-2035 04:42:56 GMT; Max-Age=315360000; Secure
Set-Cookie: zen_sso_checked=1; Path=/; Domain=.dzen.ru; Expires=Sun, 23-Mar-2025 16:42:56 GMT; Max-Age=43200; Secure; HttpOnly
Set-Cookie: zen_vk_sso_checked=0; Path=/; Domain=.dzen.ru; Expires=Sun, 23-Mar-2025 16:42:56 GMT; Max-Age=43200; Secure; HttpOnly
Set-Cookie: _yasc=NBKVCgGOxi/fAWcfP8BGfbUdBxWU+N81SDc1WR0cH7PXHtKVWgzYD8xeUuFFN5EeHw==; domain=.dzen.ru; path=/; expires=Wed, 21 Mar 2035 04:42:56 GMT; secure

HTTP/1.1 200 OK
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
Content-Length: 2007
Content-Security-Policy: default-src 'none'; frame-ancestors https://*.dzen.ru https://dzen.ru; connect-src 'self'; script-src 'nonce-295bde809d0df9fe971fbec3408e9913' 'self'; img-src 'self'
Content-Type: text/html; charset=utf-8
Date: Sun, 23 Mar 2025 04:42:56 GMT
ETag: W/"7d7-xpKofQB/ZTYlHVtwPZt9YMumFeY"
Expires: 0
Pragma: no-cache
Referrer-Policy: origin
Set-Cookie: mda2_beacon=1742704976409; Domain=.passport.yandex.ru; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Secure; Path=/
Set-Cookie: ys=c_chck.726577201; Domain=.yandex.ru; Secure; Path=/
Set-Cookie: i=YSUsnQU04iDKbxTqZM0xcxb4dU28lttvLF37SqEy/xeelRJPpEOWBjLDRZAZ9duDVL6XAlqewgqdIwKlYRZHVmPl8RU=; Domain=.yandex.ru; Expires=Wed, 21 Mar 2035 04:42:56 GMT; Secure; HttpOnly; Path=/
Set-Cookie: yandexuid=878608101742704976; Domain=.yandex.ru; Expires=Wed, 21 Mar 2035 04:42:56 GMT; Secure; Path=/
Set-Cookie: mda2_domains=dzen.ru; Domain=.passport.yandex.ru; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Secure; Path=/
Strict-Transport-Security: max-age=315360000; includeSubDomains; preload
Surrogate-Control: no-store
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-E: d
X-XSS-Protection: 1; mode=block

<body></body><script nonce='295bde809d0df9fe971fbec3408e9913'>var it = {"host":"https:\u002F\u002Fsso.dzen.ru\u002Finstall?uuid=0f17899e-a473-491f-94d3-8dd4cb6f9cc1","retpath":"https:\u002F\u002Fdzen.ru\u002Fvideo\u002Fwatch\u002F639af70a4cb0c65b51c4b724?is_autologin_ya=true"};(function() { var form = document.createElement('form'); var element1 = document.createElement('input'); var element2 = document.createElement('input'); element1.name = 'retpath'; element1.type = 'hidden'; element1.value = it.retpath; form.appendChild(element1); element2.name = 'container'; element2.type = 'hidden'; element2.value = '1742705036.10153478.FeKk5MlfdAo58CVJ.mt8P6XsJkf67A1LBEX3Qj05h5l9pIfBNoZZb9J2XGfgriB_gPQhJfWWB1ko16V-Xi3m5LMMQIe5hV8ZPOmpzcmgryupIN-pIigOV6cLtbK3fv0IGvJ0na7UhqQQk8VeLdTjWu_rcMO-E6OvuHCwxyh_43d76oGBivEIFhBPRn5KM4FLNmEo_ZKpjWMv4eX5b9puxXd7zA2nlzeRh1dkqiRAxUf-Ul-uV46okuxmE-Rv9-R3zUBolRgNI5N5uzSY_Ru0YDSY7gkcQQDXztxfWHWyUqtmihj9fvb4IZi0giikkzRuPvk7meNtEgp4JKQg81hvE7OXukZD3Av6t7RaUJF5CuEW1mKfBolKPixMKzxk7Qr2q3qDoQBkXVQDfeckFGfb-4EqnO-CvJA_S1lfxRQKL15Gq7PJtwzScjniSYnEIkY9KST7_HKdk-OSSGvqdpuKoB_JBRaGAWcWb9AklXOlOcNcw81RiJFD_6KvrqiWu803hJ6ULf61P_FchL8joYvqf9mRW6lSAmThSCVSA-A_ayr_tC-N4bTTQXpIgOP8-KGaw7EJxX9u-voeC7kmQsM0pfOwnSCjZdsf9C9OJ2-rYlykSV11cGAVmE7CWCarNhRSmaMaZx4CogLWXmEtTNKGGx_6KEzfebj0U6aT9C_NKgGpPTvw1ykEHLs_lRNbD20BuGL5uEMKsP1VWGkaD89Pddv5c7jLz6p1nVZWMUdsSt_YLA75PPWp9gZG6chLRXgD8RBfgjD95kNYNtxPPPVa60Z-UbvRK6_sKvJ9Rf6TCpD16YX0v7--lB0ITbZeX445KmT7xXfFwcBJvwMpvVT4s-JhdDtfBKaZMoHYuMx82ovqsTOxw13gdUyvMhpAvXiGv7fb2I5t5FIgVzcv-DJLS82lBmbc1jie-Z1jazpPWfptIrIWnkttzRGf6GvZoSbDD5yhcCMCMds0fCVOLhZEfs0nFVtROpig1Mp72ymlg1P0RMc0h5zW9L_gx82Al0ClrrvsLZswjpI-chFDjgVP_FrBs4nJwwMFQZ_dRFyQdu1ylURT-xDz262GO0syzBBSoHVzcMA60e6TYih05Ab33RVOIyiFjVIaMrpYxpOsO_KefCey89WzcvAu3QKNAV5ZaGvk5WZQb1rVvAzIkiLJnSMv9kuBeCaE-mBKa9HNJpBuqPNQrm7b2kz73rn6H.3o7mePJpfCbyt8PArLqJaA'; form.appendChild(element2); form.method = 'POST'; form.action = it.host; document.body.appendChild(form); form.submit();})();</script>
```

Can't get where to step further, thanks.
